# Curso JOAN 3h

In [4]:
3+7

10

# markdown # titulo
## subtitulo ## segundo titulo
### tercer tit "###" 
**en negrita** con **, en *cursiva* con *
- puntos y texto bonito

## crear variables: el fundamento de la programacion.
- Crea un recipiente para guardar un valor

In [6]:
numero = 7
numero * 3

21

## Tipologia de variables:

In [11]:
entera = 4   #integrer
decimal = 3.45   #float
texto = "hola, mi nombre es Frank"   #String
logica = True  #Booleano (/o False = 0 y True = 1
(a, b, c, d, = 4, 6, 8, 1  #Asignacion multiple)

entera * decimal
entera * logica  #Se puede operar con booleano (1)
entera * texto #opera texto: se repite las veces que entero

'hola, mi nombre es Frankhola, mi nombre es Frankhola, mi nombre es Frankhola, mi nombre es Frank'

## Comparaciones:
- Una comparacion es hacerle una pregunta de si o no a python

In [13]:
a, b, c, d, = 4, 6, 8, 1  #Asignacion multiple

a > c
a >= c
a == d #Son inguales? 2 "=" porque 1 "=" es asignar (ej, valor a una variable)
a != d #Son distintas?

True

## Condicionales:
- Estructuras de control que te permiten decidir que hacer en distintos escenarios

In [14]:
nota = 6

if nota < 5:
    if nota >= 3.5:
         print("Revisaremos el examen")
    else:
        print("Suspenso") #Identado 2 niveles    
else:
    print("Aprobado")
    if nota >= 9:
        print("Matricula de Honor")

Aprobado

## Listas: 
- Estructura de datos ordenada y muy flexible. Es como un armario de recipientes o cajones.
- *nombre_lista = []*

In [15]:
milista = [4,5,6,3,4,5,6,7,1,2,3,4]
milista[0]  #Le pedimos que abra el primer cajon.
milista[0:3]  #Nos devolvera 4,5,6, el primero al tercero no incluido
milista[-1]  #Ultimo. -2 penultimo, -3 antepenultimo...

[4, 5, 6, 3, 4, 5, 6, 7, 1, 2, 3, 4]

## Metodos y funciones:
- Los **metodos** son como funciones que cuelgan del objeto. (*objeto.xxxx*) ej .append, .count, .upper
- Para ver los metodos, poner el objeto, el "." y **darle a TAB**
- Para saber que hace el metodo, poner el cursor en medio del "()" y **pulsar Shift+TAB**
- funciones: trozo de codigo que se ejeculta independientemente. ej. sum(milista), len(milista), min(milista)

In [19]:
sum(milista) #Esto es una funcion
milista.append(77) #Esto es un metodo
milista.count(4) #Cuentame los "4" que hay en la lista
milista.sort() #Ordena la lista. No devuelve nada, solo ordena y punto.
milista.pop() #Pulsa entre los "()" y dale a Shift+TAB para ver mas info

3

## Diccionarios:
- Estructura de datos no ordenada, con etiquetas y aun mas flexible que las listas.
- *persona = {"etiqueta" : "valor"}*
- Aqui no hay 1er cajo, 2o cajon, hay muchos cajones flotando y tu eliges el cajon que tenga la etiqueta.
- Un Tweet es un JSON de tipo DICCIONARIO

In [26]:
persona = {"nombre" : "Joan", "edad" : 31, "mascota" : "Thor", "lenguajes" : ["Python", "R", "SQL", "DAX"]}
len(persona)  #Devuelve 4. 4 cajas con clave/valor
persona["edad"] #Devuelve el valor de la clave "edad"
persona["nombre"] = persona["nombre"] + " Gasull Jolis" #Anado text al valor de la clave nombre
persona["nombre"]

'Joan Gasull Jolis'

## Bucles:
- Automatiza un proceso

In [44]:
notas = [4,3,3,7,6,8,7,9,3,2,4,5,6,10]
#por cada nota en las notas que hay, ensena nota:
#for pikachu in notas:
    #print(pikachu)

#for x in notas:
 #   print("La nota es", x)

#Buvles por valor
for nota in notas:
    print("\nLa nota es: ", nota, "\n") # "\n"Salto de linea
    if nota < 5:
        if nota >= 3.5:
             print("Revisaremos el examen")
        else:
            print("Suspenso") #Identado 2 niveles    
    else:
        print("Aprobado")
        if nota >= 9:
            print("Matricula de Honor")

La nota es:  4

Revisaremos el examen

La nota es:  3

Suspenso

La nota es:  3

Suspenso

La nota es:  7

Aprobado

La nota es:  6

Aprobado

La nota es:  8

Aprobado

La nota es:  7

Aprobado

La nota es:  9

Aprobado
Matricula de Honor

La nota es:  3

Suspenso

La nota es:  2

Suspenso

La nota es:  4

Revisaremos el examen

La nota es:  5

Aprobado

La nota es:  6

Aprobado

La nota es:  10

Aprobado
Matricula de Honor

In [48]:
# Bucles por posicion (primero posicion 0,1,2,3..) Se usan cuando importa la posicion
# Son mas optimas que los for por valor

for posicion in range(len(notas)):
    print("En la posicion", posicion, "hay un", notas[posicion])

En la posicion 0 hay un 4
En la posicion 1 hay un 3
En la posicion 2 hay un 3
En la posicion 3 hay un 7
En la posicion 4 hay un 6
En la posicion 5 hay un 8
En la posicion 6 hay un 7
En la posicion 7 hay un 9
En la posicion 8 hay un 3
En la posicion 9 hay un 2
En la posicion 10 hay un 4
En la posicion 11 hay un 5
En la posicion 12 hay un 6
En la posicion 13 hay un 10

## Funciones: creacion
- Trozo de codigo **que hace lo que tu quieras** por ejemplo, una funcion avg

In [49]:
# Creamos fun que recibe un num y lo devuelve la div de la suma de los valores
# con el conteo de valores, es decir, la media.
def media (numeros):
    """
    numeros: lista o similiares
    
    """
    suma = sum(numeros)
    nnumeros = len(numeros)
    return suma/nnumeros 

media([4,5,6,7,1,2,1,2,3,4]) #Invocamos func y enviamos una lista de numeros

3.5

## PANDAS:
- Libreria de analitica de datos fundamental en Python. Es EL paquete.
- Libreria es un conjunto de funciones.
- Si no tengo la libreria, tengo que instalarla: *! pip install pandas*

In [54]:
import pandas as pd #se inicia la importacion y se le anade una abreviatura (pd)


pd.DataFrame({"persona":["Joan", "Laura", "Pau"], "edad":[31,21,34]})

  persona  edad
0    Joan    31
1   Laura    21
2     Pau    34

### Leer archivos CSV en pandas:

In [56]:
#Ruta para subir archivos, pon una "r" para corregir el formato.
r"C:\Users\Manu\Desktop\ESPECIALIZACION\Sprint 2 - SQL Introduccio\Ej8\N1.Ex.8__ credit_cards.csv"

df = pd.read_csv(r"C:\Users\Manu\Desktop\ESPECIALIZACION\Sprint 2 - SQL Introduccio\Ej8\N1.Ex.8__ credit_cards.csv")
df

,id,user_id,iban,pan,pin,cvv,track1,track2,expiring_date
0,CcU-2938,275,TR301950312213576817638661,5424465566813633,3257,984,%B8383712448554646^WovsxejDpwiev^86041142?7,%B7653863056044187=8007163336?3,10/30/22
1,CcU-2945,274,DO26854763748537475216568689,5142423821948828,9080,887,%B4621311609958661^UftuyfsSeimxn^0610628241?7,%B4149568437843501=5107140330?1,08/24/23
2,CcU-2952,273,BG45IVQL52710525608255,4556 453 55 5287,4598,438,%B2183285104307501^CddyytcUxwfdq^5907955430?9,%B6778580257827162=69068597400?7,06/29/21
3,CcU-2959,272,CR7242477244335841535,372461377349375,3583,667,%B7281111956795320^XocddijBckecd^09016253?3,%B4246154489281853=2805223916?8,02/24/23
4,CcU-2966,271,BG72LKTQ15627628377363,448566 886747 7265,4900,130,%B4728932322756223^JhlgvsuFbmwgj^72022894943?7,%B2318571115599881=8908215784?5,10/29/24
...,...,...,...,...,...,...,...,...,...
4995,CcS-9577,4996,XX158914078594808633147086,8110437271856107,5864,772,%B8110437271856107^JSUYVDJSUYVD^30010000000000...,%B8110437271856107=2601101911784272?,10/29/26
4996,CcS-9578,4997,XX991539646456110567870254,8999808823061411,2872,772,%B8999808823061411^YJXWBBYJXWBB^31090000000000...,%B8999808823061411=3411101293065061?,07/29/27
4997,CcS-9579,4998,XX296393091587170202131236,9690060468678689,8379,134,%B9690060468678689^GUZIHXGUZIHX^34120000000000...,%B9690060468678689=2411101172676621?,12/25/25
4998,CcS-9580,4999,XX781258889851950806677358,5541182364498931,9273,737,%B5541182364498931^YGHGSTYGHGST^30080000000000...,%B5541182364498931=3205101580558784?,03/27/29
4999,CcS-9581,5000,XX915670516405388124398147,2624305470167630,4336,926,%B2624305470167630^TEJVMKTEJVMK^30040000000000...,%B2624305470167630=3404101123078194?,06/29/25

### Metodos en PANDAS:

In [59]:
df.head() #Para ver la cabecera
df.tail(2) #Para ver las 2 ultimas de cola
df.describe() #Resumen estadistico de todas las var. del df. Puedo tratarlo como una tabla.

           user_id          pin          cvv
count  5000.000000  5000.000000  5000.000000
mean   2500.500000  5561.688800   553.216600
std    1443.520003  2587.423311   259.623956
min       1.000000  1001.000000   100.000000
25%    1250.750000  3299.750000   328.000000
50%    2500.500000  5622.500000   557.000000
75%    3750.250000  7814.250000   777.000000
max    5000.000000  9998.000000   999.000000

### Columnas en PANDAS:

In [ ]:
del df["year"] #Borra la columna
df["nueva columna"] = "Hola" #Creas una nueva col con "Hola","Hola"...
df["velocidad"] = df["distance"] / df["air_time"] # Creamos columna calculada, ej velocidad.

### Seleccionar informacion en PANDAS:

In [ ]:
df["air_time"] #Seleccionamos columnas. No es un df, es una serie (col de un df)
df[["air_time", "distance"]] #Seleccionas 2 columnas. Esto si es un df

df[0:5] #Seleccionas por posicion.

In [ ]:
# Seleccionamos info por posicion
#ILOC[] es raro.

df.iloc[3,2] #Fila 4 y Columna 3
df.iloc[0:5, 0:5] #Primeras 5 filas y primeras columnas

In [ ]:
# Seleccionamos info por valor/condicion.

df.loc[1:5, ["air_time", "origin"]] #Dame las filas de la 1 a la 5 y las columnas que se llamen tal.
df.loc[df["ait_time"] > 120, ["origin"]] #Dame las filas de vuelos +120min y la colm origen.
df.loc[(df["air_time"] > 120) & (df["arr_delay"] > 30), ["origin"]] #+1 seleccion. "/" para OR

In [ ]:
# Media del tiempo de vuelo de los aviones de JFK
df.loc[df["origin"] == "JFK", "air_time"].mean()

## Tablas resumen en PANDAS:
- Equivalentes a *tablas dinamicas* en Excel (Pivot Table)
- Df se pueden ordenar con **.sort_values["nom"]**

In [62]:
# Groupby para hacer tablas por filas

# Quiero ver la media de los retrasos agrupados por origen:
df.groupby(["carrier"])[["arr_delay"]].mean() #.sum()/.count()/.describe()/

In [ ]:
# Crosstab para hacer tablas de doble entrada

pd.crosstab(df["origin"],df["dest"]) #tabla de contingencia. Arriba el destino y a la izq el origen.

## Exportar df en PANDAS:
- **.to_excel("hola.xlsx")** se guarda en la carpeta donde tengas el codigo

## Graficos en PANDAS:
- Dentro de pandas hay incorporada una version simplificada de Matplot (paquete principal)

In [ ]:
#Histograma:
df["distance"].plot.hist() #o .plot.box()

#Nube de puntos:
df.plot.scatter(x = "dep_delay", y = "arr_delay") #Tenemos que asignar las x e y

#Barras (ej. de un recuento)
df.["carrier"].value_counts().plot.bar() #Primero hacemos el count value y mostramos en barras.

# Doble barra (dos variables)
df.groupby("carrier")[["arr_delay", "dep_delay"]].mean().plot.bar() #Grafico con 2 barras.